const prefectures = [
  { name: "Boké", value: "boke" },
  { name: "Boffa", value: "boffa" },
  { name: "Conakry", value: "conakry" },
  { name: "Coyah", value: "coyah" },
  { name: "Dabola", value: "dabola" },
  { name: "Dalaba", value: "dalaba" },
  { name: "Dinguiraye", value: "dinguiraye" },
  { name: "Dubréka", value: "dubreka" },
  { name: "Faranah", value: "faranah" },
  { name: "Forécariah", value: "forecariah" },
  { name: "Fria", value: "fria" },
  { name: "Gaoual", value: "gaoual" },
  { name: "Guékédou", value: "guékédou" },
  { name: "Kamsar", value: "kamsar" },
  { name: "Kankan", value: "kankan" },
  { name: "Kérouané", value: "kérouané" },
  { name: "Kindia", value: "kindia" },
  { name: "Kissidougou", value: "kissidougou" },
  { name: "Koubia", value: "koubia" },
  { name: "Koundara", value: "koundara" },
  { name: "Kouroussa", value: "kouroussa" },
  { name: "Labé", value: "labe" },
  { name: "Lélouma", value: "lelouma" },
  { name: "Lola", value: "lola" },
  { name: "Macenta", value: "macenta" },
  { name: "Mali", value: "mali" },
  { name: "Mamou", value: "mamou" },
  { name: "Mandiana", value: "mandiana" },
  { name: "Nzérékoré", value: "nzerekore" },
  { name: "Pita", value: "pita" },
  { name: "Siguiri", value: "siguiri" },
  { name: "Télimélé", value: "telimele" },
  { name: "Tougué", value: "tougue" },
  { name: "Yomou", value: "yomou" },
];

module.exports = prefectures;
